import { CharacterData } from 'src/app/model/character-data.model';
import { NumberComputedPlaceholderConfig } from 'src/app/model/placeholder.model';
import { TwoPageSheetConfig } from 'src/app/model/sheet-config.model';

function difficulte(config: Omit<NumberComputedPlaceholderConfig, 'compute'>, suffix: string, divider: number, baseValueKey?: string): NumberComputedPlaceholderConfig {
  const key = baseValueKey || config.key.replace(suffix, '');
  return {
    ...config, 
    compute: (data: CharacterData) => {
      const baseValue = parseInt(data.values[key] as any);
      if (baseValue === undefined || isNaN(baseValue)) {
        return '';
      }
      return Math.floor(baseValue / divider);
    },
  };
}

function demi(config: Omit<NumberComputedPlaceholderConfig, 'compute'>, baseValueKey?: string): NumberComputedPlaceholderConfig {
  return difficulte(config, '_2', 2, baseValueKey);
}

function cinquieme(config: Omit<NumberComputedPlaceholderConfig, 'compute'>, baseValueKey?: string): NumberComputedPlaceholderConfig {
  return difficulte(config, '_5', 5, baseValueKey);
}

export const config: TwoPageSheetConfig = {
  gameId: 'cthulhu-v7',
  sheetId: 'fr-classique',
  pageConfig: {
    pages: [ 'page-1.png', 'page-2.png' ],
    pageFormat: 'A4',
    pageWidth: 100
  },
  content: {
    pageCount: 2,
    page1: [
      { key: 'etatCivil.nom', x: 9.7, y: 5.9, width: 26.5, type: 'text-input'},
      { key: 'etatCivil.joueur', x: 10.5, y: 8, width: 25.7, type: 'text-input'},
      { key: 'etatCivil.occupation', x: 14, y: 9.9, width: 22.2, type: 'text-input'},
      { key: 'etatCivil.age', x: 9.5, y: 11.9, width: 11, type: 'text-input'},
      { key: 'etatCivil.sexe', x: 25, y: 11.9, width: 11.2, type: 'text-input'},
      { key: 'etatCivil.residence', x: 13, y: 13.7, width: 23.2, type: 'text-input'},
      { key: 'etatCivil.lieuDeNaissance', x: 17, y: 15.6, width: 19.2, type: 'text-input'},

      { key: 'caracteristiques.force', x: 44.75, y: 6.2, width: 2.1, type: 'number-input'},
      demi({ key: 'caracteristiques.force_2', x: 47.5, y: 6.2, width: 1.8, fontSize: 0.6, type: 'number-computed' }),
      cinquieme({ key: 'caracteristiques.force_5', x: 47.5, y: 7.25, width: 1.8, fontSize: 0.6, type: 'number-computed'}),

      { key: 'caracteristiques.dexterite', x: 44.75, y: 8.5, width: 2.1, type: 'number-input'},
      demi({ key: 'caracteristiques.dexterite_2', x: 47.5, y: 8.5, width: 1.8, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'caracteristiques.dexterite_5', x: 47.5, y: 9.55, width: 1.8, fontSize: 0.6, type: 'number-computed'}),

      { key: 'caracteristiques.pouvoir', x: 44.75, y: 10.9, width: 2.1, type: 'number-input'},
      demi({ key: 'caracteristiques.pouvoir_2', x: 47.5, y: 10.9, width: 1.8, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'caracteristiques.pouvoir_5', x: 47.5, y: 11.95, width: 1.8, fontSize: 0.6, type: 'number-computed'}),

      { key: 'caracteristiques.constitution', x: 44.75, y: 13.2, width: 2.1, type: 'number-input'},
      demi({ key: 'caracteristiques.constitution_2', x: 47.5, y: 13.2, width: 1.8, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'caracteristiques.constitution_5', x: 47.5, y: 14.25, width: 1.8, fontSize: 0.6, type: 'number-computed'}),

      { key: 'caracteristiques.apparence', x: 44.75, y: 15.6, width: 2.1, type: 'number-input'},
      demi({ key: 'caracteristiques.apparence_2', x: 47.5, y: 15.6, width: 1.8, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'caracteristiques.apparence_5', x: 47.5, y: 16.65, width: 1.8, fontSize: 0.6, type: 'number-computed'}),

      { key: 'caracteristiques.education', x: 58, y: 6.2, width: 2.1, type: 'number-input'},
      demi({ key: 'caracteristiques.education_2', x: 60.75, y: 6.2, width: 1.8, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'caracteristiques.education_5', x: 60.75, y: 7.25, width: 1.8, fontSize: 0.6, type: 'number-computed'}),

      { key: 'caracteristiques.taille', x: 58, y: 8.5, width: 2.1, type: 'number-input'},
      demi({ key: 'caracteristiques.taille_2', x: 60.75, y: 8.5, width: 1.8, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'caracteristiques.taille_5', x: 60.75, y: 9.55, width: 1.8, fontSize: 0.6, type: 'number-computed'}),

      { key: 'caracteristiques.intelligence', x: 58, y: 10.9, width: 2.1, type: 'number-input'},
      demi({ key: 'caracteristiques.intelligence_2', x: 60.75, y: 10.9, width: 1.8, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'caracteristiques.intelligence_5', x: 60.75, y: 11.95, width: 1.8, fontSize: 0.6, type: 'number-computed'}),
  
      { key: 'caracteristiques.mouvement', x: 58, y: 14.2, width: 2.1, type: 'number-input'},

      { key: 'pointDeVie.blessureGrave', x: 21, y: 18.2, width: 2.1, type: 'number-input'},
      { key: 'pointDeVie.max', x: 36, y: 18.2, width: 2.1, type: 'number-input'},
      { key: 'pointDeVie.actuel_00', x: 33.2, y: 20.25, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_01', x: 35.1, y: 20.25, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_02', x: 37.0, y: 20.25, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_03', x: 5.30, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_04', x: 7.18, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_05', x: 9.06, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_06', x: 10.94, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_07', x: 12.82, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_08', x: 14.70, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_09', x: 16.58, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_10', x: 18.46, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_11', x: 20.34, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_12', x: 22.22, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_13', x: 24.10, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_14', x: 25.98, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_15', x: 27.86, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_16', x: 29.74, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_17', x: 31.62, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_18', x: 33.50, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_19', x: 35.38, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeVie.actuel_20', x: 37.26, y: 21.55, width: 1.6, group: 'pointDeVie.actuel', style:'circle', type: 'checkbox-group' },

      { key: 'pointDeMagie.max', x: 36, y: 23.5, width: 2.1, type: 'number-input'},
      { key: 'pointDeMagie.actuel_00', x: 22.80, y: 25.15, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_01', x: 24.83, y: 25.15, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_02', x: 26.86, y: 25.15, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_03', x: 28.89, y: 25.15, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_04', x: 30.90, y: 25.15, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_05', x: 32.93, y: 25.15, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_06', x: 34.96, y: 25.15, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_07', x: 36.99, y: 25.15, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_08', x: 5.30, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_09', x: 7.28, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_10', x: 9.26, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_11', x: 11.24, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_12', x: 13.22, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_13', x: 15.20, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_14', x: 17.18, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_15', x: 19.16, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_16', x: 21.14, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_17', x: 23.12, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_18', x: 25.10, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_19', x: 27.08, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_20', x: 29.06, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_21', x: 31.04, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_22', x: 33.02, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_23', x: 35.00, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'pointDeMagie.actuel_24', x: 36.98, y: 26.5, width: 1.6, group: 'pointDeMagie.actuel', style:'circle', type: 'checkbox-group' },

      { key: 'santeMentale.folieTemporaire', x: 53.5, y: 18.2, width: 2.1, type: 'number-input'},
      { key: 'santeMentale.foliePersistente', x: 69, y: 18.2, width: 2.1, type: 'number-input'},
      { key: 'santeMentale.initial', x: 82, y: 18.2, width: 2.1, type: 'number-input'},
      { key: 'santeMentale.max', x: 91, y: 18.2, width: 2.1, type: 'number-input'},
      { key: 'santeMentale.actuel_01', x: 64.10, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_02', x: 66.47, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_03', x: 68.84, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_04', x: 71.21, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_05', x: 73.58, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_06', x: 75.95, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_07', x: 78.32, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_08', x: 80.69, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_09', x: 83.06, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_10', x: 85.43, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_11', x: 87.80, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_12', x: 90.17, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_13', x: 92.54, y: 20.35, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_14', x: 42.70, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_15', x: 45.07, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_16', x: 47.44, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_17', x: 49.81, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_18', x: 52.18, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_19', x: 54.55, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_20', x: 56.92, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_21', x: 59.29, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_22', x: 61.66, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_23', x: 64.03, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_24', x: 66.40, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_25', x: 68.77, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_26', x: 71.14, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_27', x: 73.51, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_28', x: 75.88, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_29', x: 78.25, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_30', x: 80.62, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_31', x: 82.99, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_32', x: 85.36, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_33', x: 87.73, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_34', x: 90.10, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_35', x: 92.47, y: 21.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_36', x: 42.70, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_37', x: 45.07, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_38', x: 47.44, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_39', x: 49.81, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_40', x: 52.18, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_41', x: 54.55, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_42', x: 56.92, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_43', x: 59.29, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_44', x: 61.66, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_45', x: 64.03, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_46', x: 66.40, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_47', x: 68.77, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_48', x: 71.14, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_49', x: 73.51, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_50', x: 75.88, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_51', x: 78.25, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_52', x: 80.62, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_53', x: 82.99, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_54', x: 85.36, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_55', x: 87.73, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_56', x: 90.10, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_57', x: 92.47, y: 23.40, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_58', x: 42.70, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_59', x: 45.07, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_60', x: 47.44, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_61', x: 49.81, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_62', x: 52.18, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_63', x: 54.55, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_64', x: 56.92, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_65', x: 59.29, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_66', x: 61.66, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_67', x: 64.03, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_68', x: 66.40, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_69', x: 68.77, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_70', x: 71.14, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_71', x: 73.51, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_72', x: 75.88, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_73', x: 78.25, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_74', x: 80.62, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_75', x: 82.99, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_76', x: 85.36, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_77', x: 87.73, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_78', x: 90.10, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_79', x: 92.47, y: 24.85, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_80', x: 42.60, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_81', x: 45.05, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_82', x: 47.50, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_83', x: 49.95, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_84', x: 52.40, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_85', x: 54.85, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_86', x: 57.30, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_87', x: 59.75, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_88', x: 62.20, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_89', x: 64.65, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_90', x: 67.10, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_91', x: 69.55, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_92', x: 72.00, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_93', x: 74.45, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_94', x: 76.90, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_95', x: 79.35, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_96', x: 81.80, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_97', x: 84.25, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_98', x: 86.70, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_99', x: 89.15, y: 26.30, width: 1.7, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'santeMentale.actuel_100', x: 92.00, y: 26.15, width: 2.0, group: 'santeMentale.actuel', style:'circle', type: 'checkbox-group' },

      { key: 'chance.actuel_01', x: 26.55, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_02', x: 28.99, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_03', x: 31.43, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_04', x: 33.87, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_05', x: 36.31, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_06', x: 38.75, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_07', x: 41.19, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_08', x: 43.63, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_09', x: 46.07, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_10', x: 48.51, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_11', x: 50.95, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_12', x: 53.39, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_13', x: 55.83, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_14', x: 58.27, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_15', x: 60.71, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_16', x: 63.15, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_17', x: 65.59, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_18', x: 68.03, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_19', x: 70.47, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_20', x: 72.91, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_21', x: 75.35, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_22', x: 77.79, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_23', x: 80.23, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_24', x: 82.67, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_25', x: 85.11, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_26', x: 87.55, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_27', x: 89.99, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_28', x: 92.43, y: 28.50, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_29', x: 5.30, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_30', x: 7.79, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_31', x: 10.28, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_32', x: 12.77, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_33', x: 15.26, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_34', x: 17.75, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_35', x: 20.24, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_36', x: 22.73, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_37', x: 25.22, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_38', x: 27.71, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_39', x: 30.20, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_40', x: 32.69, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_41', x: 35.18, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_42', x: 37.67, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_43', x: 40.16, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_44', x: 42.65, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_45', x: 45.14, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_46', x: 47.63, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_47', x: 50.12, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_48', x: 52.61, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_49', x: 55.10, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_50', x: 57.59, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_51', x: 60.08, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_52', x: 62.57, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_53', x: 65.06, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_54', x: 67.55, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_55', x: 70.04, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_56', x: 72.53, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_57', x: 75.02, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_58', x: 77.51, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_59', x: 80.00, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_60', x: 82.49, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_61', x: 84.98, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_62', x: 87.47, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_63', x: 89.96, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_64', x: 92.45, y: 29.85, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_65', x: 5.30, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_66', x: 7.77, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_67', x: 10.24, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_68', x: 12.71, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_69', x: 15.18, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_70', x: 17.65, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_71', x: 20.12, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_72', x: 22.59, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_73', x: 25.06, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_74', x: 27.53, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_75', x: 30.00, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_76', x: 32.47, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_77', x: 34.94, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_78', x: 37.41, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_79', x: 39.88, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_80', x: 42.35, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_81', x: 44.82, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_82', x: 47.29, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_83', x: 49.76, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_84', x: 52.23, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_85', x: 54.70, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_86', x: 57.17, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_87', x: 59.64, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_88', x: 62.11, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_89', x: 64.58, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_90', x: 67.05, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_91', x: 69.52, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_92', x: 71.99, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_93', x: 74.46, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_94', x: 76.93, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_95', x: 79.40, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_96', x: 81.87, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_97', x: 84.34, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_98', x: 86.81, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_99', x: 89.28, y: 31.10, width: 1.7, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },
      { key: 'chance.actuel_100', x: 91.85, y: 30.95, width: 2, group: 'chance.actuel', style:'circle', type: 'checkbox-group' },

      { key: 'competences.anthropologie_succes', x: 4.6, y: 39.9, width: 1.4, type: 'checkbox'},
      { key: 'competences.archeologie_succes', x: 4.6, y: 41.556, width: 1.4, type: 'checkbox'},
      { key: 'competences.artsEtMetiers_succes', x: 4.6, y: 43.22, width: 1.4, type: 'checkbox'},
      { key: 'competences.artsEtMetiers1_succes', x: 4.6, y: 44.88, width: 1.4, type: 'checkbox'},
      { key: 'competences.artsEtMetiers2_succes', x: 4.6, y: 46.54, width: 1.4, type: 'checkbox'},
      { key: 'competences.artsEtMetiers3_succes', x: 4.6, y: 48.1, width: 1.4, type: 'checkbox'},
      { key: 'competences.baratin_succes', x: 4.6, y: 49.86, width: 1.4, type: 'checkbox'},
      { key: 'competences.bibliotheque_succes', x: 4.6, y: 51.52, width: 1.4, type: 'checkbox'},
      { key: 'competences.charme_succes', x: 4.6, y: 53.18, width: 1.4, type: 'checkbox'},
      { key: 'competences.armesDePoing_succes', x: 4.6, y: 56.5, width: 1.4, type: 'checkbox'},
      { key: 'competences.fusils_succes', x: 4.6, y: 58.16, width: 1.4, type: 'checkbox'},
      { key: 'competences.combatADistance1_succes', x: 4.6, y: 59.82, width: 1.4, type: 'checkbox'},
      { key: 'competences.combatADistance2_succes', x: 4.6, y: 61.48, width: 1.4, type: 'checkbox'},
      { key: 'competences.corpsACorps_succes', x: 4.6, y: 64.8, width: 1.4, type: 'checkbox'},
      { key: 'competences.combatRapproche1_succes', x: 4.6, y: 66.46, width: 1.4, type: 'checkbox'},
      { key: 'competences.combatRapproche2_succes', x: 4.6, y: 68.12, width: 1.4, type: 'checkbox'},
      { key: 'competences.comptabilite_succes', x: 4.6, y: 69.8, width: 1.4, type: 'checkbox'},
      { key: 'competences.conduite_succes', x: 4.6, y: 71.46, width: 1.4, type: 'checkbox'},
      { key: 'competences.conduiteEnginLourd_succes', x: 4.6, y: 73.12, width: 1.4, type: 'checkbox'},
      { key: 'competences.crochetage_succes', x: 4.6, y: 76.44, width: 1.4, type: 'checkbox'},

      { key: 'competences.anthropologie', x: 23.6, y: 39.2, width: 2.8, type: 'number-input'},
      { key: 'competences.archeologie', x: 23.6, y: 40.86, width: 2.8, type: 'number-input'},
      { key: 'competences.artsEtMetiers', x: 23.6, y: 42.52, width: 2.8, type: 'number-input'},
      { key: 'competences.artsEtMetiers1_label', x: 6.5, y: 44.18, width: 16.8, type: 'text-input'},
      { key: 'competences.artsEtMetiers1_value', x: 23.6, y: 44.18, width: 2.8, type: 'number-input'},
      { key: 'competences.artsEtMetiers2_label', x: 6.5, y: 45.84, width: 16.8, type: 'text-input'},
      { key: 'competences.artsEtMetiers2_value', x: 23.6, y: 45.84, width: 2.8, type: 'number-input'},
      { key: 'competences.artsEtMetiers3_label', x: 6.5, y: 47.57, width: 16.8, type: 'text-input'},
      { key: 'competences.artsEtMetiers3_value', x: 23.6, y: 47.5, width: 2.8, type: 'number-input'},
      { key: 'competences.baratin', x: 23.6, y: 49.16, width: 2.8, type: 'number-input'},
      { key: 'competences.bibliotheque', x: 23.6, y: 50.82, width: 2.8, type: 'number-input'},
      { key: 'competences.charme', x: 23.6, y: 52.48, width: 2.8, type: 'number-input'},
      { key: 'competences.armesDePoing', x: 23.6, y: 55.8, width: 2.8, type: 'number-input'},
      { key: 'competences.fusils', x: 23.6, y: 57.46, width: 2.8, type: 'number-input'},
      { key: 'competences.combatADistance1_label', x: 6.5, y: 59.12, width: 16.8, type: 'text-input'},
      { key: 'competences.combatADistance1_value', x: 23.6, y: 59.12, width: 2.8, type: 'number-input'},
      { key: 'competences.combatADistance2_label', x: 6.5, y: 60.78, width: 16.8, type: 'text-input'},
      { key: 'competences.combatADistance2_value', x: 23.6, y: 60.78, width: 2.8, type: 'number-input'},
      { key: 'competences.corpsACorps', x: 23.6, y: 64.1, width: 2.8, type: 'number-input'},
      { key: 'competences.combatRapproche1_label', x: 6.5, y: 65.76, width: 16.8, type: 'text-input'},
      { key: 'competences.combatRapproche1_value', x: 23.6, y: 65.76, width: 2.8, type: 'number-input'},
      { key: 'competences.combatRapproche2_label', x: 6.5, y: 67.42, width: 16.8, type: 'text-input'},
      { key: 'competences.combatRapproche2_value', x: 23.6, y: 67.42, width: 2.8, type: 'number-input'},
      { key: 'competences.comptabilite', x: 23.6, y: 69.1, width: 2.8, type: 'number-input'},
      { key: 'competences.conduite', x: 23.6, y: 70.76, width: 2.8, type: 'number-input'},
      { key: 'competences.conduiteEnginLourd', x: 23.6, y: 72.42, width: 2.8, type: 'number-input'},
      { key: 'competences.credit', x: 23.6, y: 74.08, width: 2.8, type: 'number-input'},
      { key: 'competences.crochetage', x: 23.6, y: 75.74, width: 2.8, type: 'number-input'},

      demi({ key: 'competences.anthropologie_2', x: 29.2, y: 39.7, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.archeologie_2', x: 29.2, y: 41.36, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.artsEtMetiers_2', x: 29.2, y: 43.02, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.artsEtMetiers1_value_2', x: 29.2, y: 44.68, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.artsEtMetiers2_value_2', x: 29.2, y: 46.34, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.artsEtMetiers3_value_2', x: 29.2, y: 48, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.baratin_2', x: 29.2, y: 49.66, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.bibliotheque_2', x: 29.2, y: 51.32, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.charme_2', x: 29.2, y: 52.98, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.armesDePoing_2', x: 29.2, y: 56.3, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.fusils_2', x: 29.2, y: 57.96, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.combatADistance1_value_2', x: 29.2, y: 59.62, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.combatADistance2_value_2', x: 29.2, y: 61.28, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.corpsACorps_2', x: 29.2, y: 64.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.combatRapproche1_value_2', x: 29.2, y: 66.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.combatRapproche2_value_2', x: 29.2, y: 67.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.comptabilite_2', x: 29.2, y: 69.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.conduite_2', x: 29.2, y: 71.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.conduiteEnginLourd_2', x: 29.2, y: 72.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.credit_2', x: 29.2, y: 74.58, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.crochetage_2', x: 29.2, y: 76.24, width: 1.6, fontSize: 0.6, type: 'number-computed'}),

      cinquieme({ key: 'competences.anthropologie_5', x: 31.2, y: 39.7, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.archeologie_5', x: 31.2, y: 41.36, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.artsEtMetiers_5', x: 31.2, y: 43.02, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.artsEtMetiers1_value_5', x: 31.2, y: 44.68, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.artsEtMetiers2_value_5', x: 31.2, y: 46.34, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.artsEtMetiers3_value_5', x: 31.2, y: 48, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.baratin_5', x: 31.2, y: 49.66, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.bibliotheque_5', x: 31.2, y: 51.32, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.charme_5', x: 31.2, y: 52.98, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.armesDePoing_5', x: 31.2, y: 56.3, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.fusils_5', x: 31.2, y: 57.96, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.combatADistance1_value_5', x: 31.2, y: 59.62, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.combatADistance2_value_5', x: 31.2, y: 61.28, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.corpsACorps_5', x: 31.2, y: 64.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.combatRapproche1_value_5', x: 31.2, y: 66.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.combatRapproche2_value_5', x: 31.2, y: 67.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.comptabilite_5', x: 31.2, y: 69.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.conduite_5', x: 31.2, y: 71.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.conduiteEnginLourd_5', x: 31.2, y: 72.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.credit_5', x: 31.2, y: 74.58, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.crochetage_5', x: 31.2, y: 76.24, width: 1.6, fontSize: 0.6, type: 'number-computed'}),

      { key: 'competences.discretion_succes', x: 36.0, y: 39.9, width: 1.4, type: 'checkbox'},
      { key: 'competences.droit_succes', x: 36.0, y: 41.56, width: 1.4, type: 'checkbox'},
      { key: 'competences.ecouter_succes', x: 36.0, y: 43.22, width: 1.4, type: 'checkbox'},
      { key: 'competences.electricite_succes', x: 36.0, y: 44.88, width: 1.4, type: 'checkbox'},
      { key: 'competences.equitation_succes', x: 36.0, y: 46.54, width: 1.4, type: 'checkbox'},
      { key: 'competences.esquive_succes', x: 36.0, y: 48.2, width: 1.4, type: 'checkbox'},
      { key: 'competences.estimation_succes', x: 36.0, y: 49.86, width: 1.4, type: 'checkbox'},
      { key: 'competences.grimper_succes', x: 36.0, y: 51.52, width: 1.4, type: 'checkbox'},
      { key: 'competences.histoire_succes', x: 36.0, y: 53.18, width: 1.4, type: 'checkbox'},
      { key: 'competences.imposture_succes', x: 36.0, y: 54.84, width: 1.4, type: 'checkbox'},
      { key: 'competences.intimidation_succes', x: 36.0, y: 56.5, width: 1.4, type: 'checkbox'},
      { key: 'competences.lancer_succes', x: 36.0, y: 58.16, width: 1.4, type: 'checkbox'},
      { key: 'competences.langueMaternelle_succes', x: 36.0, y: 59.82, width: 1.4, type: 'checkbox'},
      { key: 'competences.langue1_succes', x: 36.0, y: 63.14, width: 1.4, type: 'checkbox'},
      { key: 'competences.langue2_succes', x: 36.0, y: 64.8, width: 1.4, type: 'checkbox'},
      { key: 'competences.langue3_succes', x: 36.0, y: 66.46, width: 1.4, type: 'checkbox'},
      { key: 'competences.mecanique_succes', x: 36.0, y: 68.12, width: 1.4, type: 'checkbox'},
      { key: 'competences.medecine_succes', x: 36.0, y: 69.8, width: 1.4, type: 'checkbox'},
      { key: 'competences.nager_succes', x: 36.0, y: 73.12, width: 1.4, type: 'checkbox'},
      { key: 'competences.naturalisme_succes', x: 36.0, y: 74.78, width: 1.4, type: 'checkbox'},
      { key: 'competences.occultisme_succes', x: 36.0, y: 76.44, width: 1.4, type: 'checkbox'},

      { key: 'competences.discretion', x: 55.2, y: 39.2, width: 2.8, type: 'number-input'},
      { key: 'competences.droit', x: 55.2, y: 40.86, width: 2.8, type: 'number-input'},
      { key: 'competences.ecouter', x: 55.2, y: 42.52, width: 2.8, type: 'number-input'},
      { key: 'competences.electricite', x: 55.2, y: 44.18, width: 2.8, type: 'number-input'},
      { key: 'competences.equitation', x: 55.2, y: 45.84, width: 2.8, type: 'number-input'},
      { key: 'competences.esquive', x: 55.2, y: 47.5, width: 2.8, type: 'number-input'},
      { key: 'competences.estimation', x: 55.2, y: 49.16, width: 2.8, type: 'number-input'},
      { key: 'competences.grimper', x: 55.2, y: 50.82, width: 2.8, type: 'number-input'},
      { key: 'competences.histoire', x: 55.2, y: 52.48, width: 2.8, type: 'number-input'},
      { key: 'competences.imposture', x: 55.2, y: 54.14, width: 2.8, type: 'number-input'},
      { key: 'competences.intimidation', x: 55.2, y: 55.8, width: 2.8, type: 'number-input'},
      { key: 'competences.lancer', x: 55.2, y: 57.46, width: 2.8, type: 'number-input'},
      { key: 'competences.langueMaternelle', x: 55.2, y: 59.12, width: 2.8, type: 'number-input'},
      { key: 'competences.langueMaternelle_langue', x: 52, y: 60.78, width: 8, type: 'text-input'},
      { key: 'competences.langue1_label', x: 38.2, y: 62.44, width: 16.8, type: 'text-input'},
      { key: 'competences.langue1_value', x: 55.2, y: 62.44, width: 2.8, type: 'number-input'},
      { key: 'competences.langue2_label', x: 38.2, y: 64.1, width: 16.8, type: 'text-input'},
      { key: 'competences.langue2_value', x: 55.2, y: 64.1, width: 2.8, type: 'number-input'},
      { key: 'competences.langue3_label', x: 38.2, y: 65.76, width: 16.8, type: 'text-input'},
      { key: 'competences.langue3_value', x: 55.2, y: 65.76, width: 2.8, type: 'number-input'},
      { key: 'competences.mecanique', x: 55.2, y: 67.42, width: 2.8, type: 'number-input'},
      { key: 'competences.medecine', x: 55.2, y: 69.1, width: 2.8, type: 'number-input'},
      { key: 'competences.mytheDeCthulhu', x: 55.2, y: 70.76, width: 2.8, type: 'number-input'},
      { key: 'competences.nager', x: 55.2, y: 72.42, width: 2.8, type: 'number-input'},
      { key: 'competences.naturalisme', x: 55.2, y: 74.08, width: 2.8, type: 'number-input'},
      { key: 'competences.occultisme', x: 55.2, y: 75.74, width: 2.8, type: 'number-input'},
      
      demi({ key: 'competences.discretion_2', x: 60.5, y: 39.7, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.droit_2', x: 60.5, y: 41.36, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.ecouter_2', x: 60.5, y: 43.02, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.electricite_2', x: 60.5, y: 44.68, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.equitation_2', x: 60.5, y: 46.34, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.esquive', x: 60.5, y: 48, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.estimation', x: 60.5, y: 49.66, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.grimper_2', x: 60.5, y: 51.32, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.histoire', x: 60.5, y: 52.98, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.imposture_2', x: 60.5, y: 54.64, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.intimidation_2', x: 60.5, y: 56.3, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.lancer_2', x: 60.5, y: 57.96, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.langueMaternelle', x: 60.5, y: 59.62, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.langue1_value', x: 60.5, y: 62.94, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.langue2_value', x: 60.5, y: 64.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.langue3_value', x: 60.5, y: 66.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.mecanique_2', x: 60.5, y: 67.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.medecine_2', x: 60.5, y: 69.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.mytheDeCthulhu', x: 60.5, y: 71.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.nager_2', x: 60.5, y: 72.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.naturalisme_2', x: 60.5, y: 74.58, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.occultisme_2', x: 60.5, y: 76.24, width: 1.6, fontSize: 0.6, type: 'number-computed'}),

      cinquieme({ key: 'competences.discretion_5', x: 62.5, y: 39.7, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.droit', x: 62.5, y: 41.36, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.ecouter', x: 62.5, y: 43.02, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.electricite', x: 62.5, y: 44.68, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.equitation', x: 62.5, y: 46.34, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.esquive', x: 62.5, y: 48, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.estimation', x: 62.5, y: 49.66, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.grimper', x: 62.5, y: 51.32, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.histoire', x: 62.5, y: 52.98, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.imposture', x: 62.5, y: 54.64, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.intimidation', x: 62.5, y: 56.3, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.lancer', x: 62.5, y: 57.96, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.langueMaternelle', x: 62.5, y: 59.62, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.langue1_value', x: 62.5, y: 62.94, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.langue2_value', x: 62.5, y: 64.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.langue3_value', x: 62.5, y: 66.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.mecanique', x: 62.5, y: 67.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.medecine', x: 62.5, y: 69.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.mytheDeCthulhu', x: 62.5, y: 71.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.nager', x: 62.5, y: 72.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.naturalisme', x: 62.5, y: 74.58, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.occultisme', x: 62.5, y: 76.24, width: 1.6, fontSize: 0.6, type: 'number-computed'}),

      { key: 'competences.orientation_succes', x: 66.9, y: 39.9, width: 1.4, type: 'checkbox'},
      { key: 'competences.persuasion_succes', x: 66.9, y: 41.56, width: 1.4, type: 'checkbox'},
      { key: 'competences.pickpocket_succes', x: 66.9, y: 43.22, width: 1.4, type: 'checkbox'},
      { key: 'competences.pilotage_succes', x: 66.9, y: 44.88, width: 1.4, type: 'checkbox'},
      { key: 'competences.pilotage1_succes', x: 66.9, y: 46.54, width: 1.4, type: 'checkbox'},
      { key: 'competences.pister_succes', x: 66.9, y: 48.2, width: 1.4, type: 'checkbox'},
      { key: 'competences.plongee_succes', x: 66.9, y: 49.86, width: 1.4, type: 'checkbox'},
      { key: 'competences.premiersSoins_succes', x: 66.9, y: 51.52, width: 1.4, type: 'checkbox'},
      { key: 'competences.psychanalyse_succes', x: 66.9, y: 53.18, width: 1.4, type: 'checkbox'},
      { key: 'competences.psychologie_succes', x: 66.9, y: 54.84, width: 1.4, type: 'checkbox'},
      { key: 'competences.sauter_succes', x: 66.9, y: 56.5, width: 1.4, type: 'checkbox'},
      { key: 'competences.sciences_succes', x: 66.9, y: 58.16, width: 1.4, type: 'checkbox'},
      { key: 'competences.sciences1_succes', x: 66.9, y: 59.82, width: 1.4, type: 'checkbox'},
      { key: 'competences.sciences2_succes', x: 66.9, y: 61.48, width: 1.4, type: 'checkbox'},
      { key: 'competences.sciences3_succes', x: 66.9, y: 63.14, width: 1.4, type: 'checkbox'},
      { key: 'competences.survie_succes', x: 66.9, y: 64.8, width: 1.4, type: 'checkbox'},
      { key: 'competences.survie1_succes', x: 66.9, y: 66.46, width: 1.4, type: 'checkbox'},
      { key: 'competences.trouveObjetCache_succes', x: 66.9, y: 68.12, width: 1.4, type: 'checkbox'},
      { key: 'competences.toc1_succes', x: 66.9, y: 69.8, width: 1.4, type: 'checkbox'},
      { key: 'competences.toc2_succes', x: 66.9, y: 71.46, width: 1.4, type: 'checkbox'},
      { key: 'competences.toc3_succes', x: 66.9, y: 73.12, width: 1.4, type: 'checkbox'},
      { key: 'competences.toc4_succes', x: 66.9, y: 74.78, width: 1.4, type: 'checkbox'},
      { key: 'competences.toc5_succes', x: 66.9, y: 76.44, width: 1.4, type: 'checkbox'},

      { key: 'competences.orientation', x: 85.8, y: 39.2, width: 2.8, type: 'number-input'},
      { key: 'competences.persuasion', x: 85.8, y: 40.86, width: 2.8, type: 'number-input'},
      { key: 'competences.pickpocket', x: 85.8, y: 42.52, width: 2.8, type: 'number-input'},
      { key: 'competences.pilotage', x: 85.8, y: 44.18, width: 2.8, type: 'number-input'},
      { key: 'competences.pilotage1_label', x: 69, y: 45.84, width: 16.8, type: 'text-input'},
      { key: 'competences.pilotage1_value', x: 85.8, y: 45.84, width: 2.8, type: 'number-input'},
      { key: 'competences.pister', x: 85.8, y: 47.5, width: 2.8, type: 'number-input'},
      { key: 'competences.plongee', x: 85.8, y: 49.16, width: 2.8, type: 'number-input'},
      { key: 'competences.premiersSoins', x: 85.8, y: 50.82, width: 2.8, type: 'number-input'},
      { key: 'competences.psychanalyse', x: 85.8, y: 52.48, width: 2.8, type: 'number-input'},
      { key: 'competences.psychologie', x: 85.8, y: 54.14, width: 2.8, type: 'number-input'},
      { key: 'competences.sauter', x: 85.8, y: 55.8, width: 2.8, type: 'number-input'},
      { key: 'competences.sciences', x: 85.8, y: 57.46, width: 2.8, type: 'number-input'},
      { key: 'competences.sciences1_label', x: 69, y: 59.12, width: 16.8, type: 'text-input'},
      { key: 'competences.sciences1_value', x: 85.8, y: 59.12, width: 2.8, type: 'number-input'},
      { key: 'competences.sciences2_label', x: 69, y: 60.78, width: 16.8, type: 'text-input'},
      { key: 'competences.sciences2_value', x: 85.8, y: 60.78, width: 2.8, type: 'number-input'},
      { key: 'competences.sciences3_label', x: 69, y: 62.44, width: 16.8, type: 'text-input'},
      { key: 'competences.sciences3_value', x: 85.8, y: 62.44, width: 2.8, type: 'number-input'},
      { key: 'competences.survie', x: 85.8, y: 64.1, width: 2.8, type: 'number-input'},
      { key: 'competences.survie1_label', x: 69, y: 65.76, width: 16.8, type: 'text-input'},
      { key: 'competences.survie1_value', x: 85.8, y: 65.76, width: 2.8, type: 'number-input'},
      { key: 'competences.trouveObjetCache', x: 85.8, y: 67.42, width: 2.8, type: 'number-input'},
      { key: 'competences.toc1_label', x: 69, y: 69.1, width: 16.8, type: 'text-input'},
      { key: 'competences.toc1_value', x: 85.8, y: 69.1, width: 2.8, type: 'number-input'},
      { key: 'competences.toc2_label', x: 69, y: 70.76, width: 16.8, type: 'text-input'},
      { key: 'competences.toc2_value', x: 85.8, y: 70.76, width: 2.8, type: 'number-input'},
      { key: 'competences.toc3_label', x: 69, y: 72.42, width: 16.8, type: 'text-input'},
      { key: 'competences.toc3_value', x: 85.8, y: 72.42, width: 2.8, type: 'number-input'},
      { key: 'competences.toc4_label', x: 69, y: 74.08, width: 16.8, type: 'text-input'},
      { key: 'competences.toc4_value', x: 85.8, y: 74.08, width: 2.8, type: 'number-input'},
      { key: 'competences.toc5_label', x: 69, y: 75.74, width: 16.8, type: 'text-input'},
      { key: 'competences.toc5_value', x: 85.8, y: 75.74, width: 2.8, type: 'number-input'},

      demi({ key: 'competences.orientation_2', x: 91.4, y: 39.7, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.persuasion_2', x: 91.4, y: 41.36, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.pickpocket_2', x: 91.4, y: 43.02, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.pilotage_2', x: 91.4, y: 44.68, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.pilotage1_value_2', x: 91.4, y: 46.34, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.pister_2', x: 91.4, y: 48, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.plongee_2', x: 91.4, y: 49.66, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.premiersSoins_2', x: 91.4, y: 51.32, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.psychanalyse_2', x: 91.4, y: 52.98, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.psychologie_2', x: 91.4, y: 54.64, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.sauter_2', x: 91.4, y: 56.3, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.sciences_2', x: 91.4, y: 57.96, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.sciences1_value_2', x: 91.4, y: 59.62, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.sciences2_value_2', x: 91.4, y: 61.28, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.sciences3_value_2', x: 91.4, y: 62.94, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.survie_2', x: 91.4, y: 64.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.survie1_value_2', x: 91.4, y: 66.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.trouveObjetCache_2', x: 91.4, y: 67.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.toc1_value_2', x: 91.4, y: 69.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.toc2_value_2', x: 91.4, y: 71.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.toc3_value_2', x: 91.4, y: 72.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.toc4_value_2', x: 91.4, y: 74.58, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      demi({ key: 'competences.toc5_value_2', x: 91.4, y: 76.24, width: 1.6, fontSize: 0.6, type: 'number-computed'}),

      cinquieme({ key: 'competences.orientation_5', x: 93.4, y: 39.7, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.persuasion_5', x: 93.4, y: 41.36, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.pickpocket_5', x: 93.4, y: 43.02, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.pilotage_5', x: 93.4, y: 44.68, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.pilotage1_value_5', x: 93.4, y: 46.34, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.pister_5', x: 93.4, y: 48, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.plongee_5', x: 93.4, y: 49.66, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.premiersSoins_5', x: 93.4, y: 51.32, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.psychanalyse_5', x: 93.4, y: 52.98, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.psychologie_5', x: 93.4, y: 54.64, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.sauter_5', x: 93.4, y: 56.3, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.sciences_5', x: 93.4, y: 57.96, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.sciences1_value_5', x: 93.4, y: 59.62, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.sciences2_value_5', x: 93.4, y: 61.28, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.sciences3_value_5', x: 93.4, y: 62.94, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.survie_5', x: 93.4, y: 64.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.survie1_value_5', x: 93.4, y: 66.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.trouveObjetCache_5', x: 93.4, y: 67.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.toc1_value_5', x: 93.4, y: 69.6, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.toc2_value_5', x: 93.4, y: 71.26, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.toc3_value_5', x: 93.4, y: 72.92, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.toc4_value_5', x: 93.4, y: 74.58, width: 1.6, fontSize: 0.6, type: 'number-computed'}),
      cinquieme({ key: 'competences.toc5_value_5', x: 93.4, y: 76.24, width: 1.6, fontSize: 0.6, type: 'number-computed'}),

      { key: 'armes.cac_ordinaire', x: 14.5, y: 86.4, width: 5.5, type: 'text-input'},
      { key: 'armes.cac_majeur', x: 21.5, y: 86.4, width: 5.5, type: 'text-input'},
      { key: 'armes.cac_extreme', x: 28.5, y: 86.4, width: 5.5, type: 'text-input'},

      { key: 'armes.arme1_label', x: 3, y: 88.4, width: 10.5, fontSize: 0.65, type: 'text-input'},
      { key: 'armes.arme1_ordinaire', x: 14.5, y: 88.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme1_majeur', x: 21.5, y: 88.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme1_extreme', x: 28.5, y: 88.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme1_degats', x: 35.5, y: 88.4, width: 8.5, type: 'text-input'},
      { key: 'armes.arme1_portee', x: 45.5, y: 88.4, width: 7.5, type: 'text-input'},
      { key: 'armes.arme1_cadence', x: 54, y: 88.4, width: 7, type: 'text-input'},
      { key: 'armes.arme1_capacite', x: 63, y: 88.4, width: 6, type: 'text-input'},
      { key: 'armes.arme1_panne', x: 70.5, y: 88.4, width: 6, type: 'text-input'},

      { key: 'armes.arme2_label', x: 3, y: 90.4, width: 10.5, fontSize: 0.65, type: 'text-input'},
      { key: 'armes.arme2_ordinaire', x: 14.5, y: 90.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme2_majeur', x: 21.5, y: 90.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme2_extreme', x: 28.5, y: 90.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme2_degats', x: 35.5, y: 90.4, width: 8.5, type: 'text-input'},
      { key: 'armes.arme2_portee', x: 45.5, y: 90.4, width: 7.5, type: 'text-input'},
      { key: 'armes.arme2_cadence', x: 54, y: 90.4, width: 7, type: 'text-input'},
      { key: 'armes.arme2_capacite', x: 63, y: 90.4, width: 6, type: 'text-input'},
      { key: 'armes.arme2_panne', x: 70.5, y: 90.4, width: 6, type: 'text-input'},

      { key: 'armes.arme3_label', x: 3, y: 92.4, width: 10.5, fontSize: 0.65, type: 'text-input'},
      { key: 'armes.arme3_ordinaire', x: 14.5, y: 92.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme3_majeur', x: 21.5, y: 92.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme3_extreme', x: 28.5, y: 92.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme3_degats', x: 35.5, y: 92.4, width: 8.5, type: 'text-input'},
      { key: 'armes.arme3_portee', x: 45.5, y: 92.4, width: 7.5, type: 'text-input'},
      { key: 'armes.arme3_cadence', x: 54, y: 92.4, width: 7, type: 'text-input'},
      { key: 'armes.arme3_capacite', x: 63, y: 92.4, width: 6, type: 'text-input'},
      { key: 'armes.arme3_panne', x: 70.5, y: 92.4, width: 6, type: 'text-input'},

      { key: 'armes.arme4_label', x: 3, y: 94.4, width: 10.5, fontSize: 0.65, type: 'text-input'},
      { key: 'armes.arme4_ordinaire', x: 14.5, y: 94.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme4_majeur', x: 21.5, y: 94.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme4_extreme', x: 28.5, y: 94.4, width: 5.5, type: 'text-input'},
      { key: 'armes.arme4_degats', x: 35.5, y: 94.4, width: 8.5, type: 'text-input'},
      { key: 'armes.arme4_portee', x: 45.5, y: 94.4, width: 7.5, type: 'text-input'},
      { key: 'armes.arme4_cadence', x: 54, y: 94.4, width: 7, type: 'text-input'},
      { key: 'armes.arme4_capacite', x: 63, y: 94.4, width: 6, type: 'text-input'},
      { key: 'armes.arme4_panne', x: 70.5, y: 94.4, width: 6, type: 'text-input'},

      { key: 'combat.impact', x: 89.3, y: 85.1, width: 2.1, type: 'number-input'},
      { key: 'combat.carrure', x: 89.3, y: 88.1, width: 2.1, type: 'number-input'},
      { key: 'combat.esquive', x: 89.3, y: 91.3, width: 2.1, type: 'number-computed', compute: (data) => data.values['competences.esquive']},
      demi({ key: 'combat.esquive_2', x: 92.2, y: 91.3, width: 1.5, fontSize: 0.5, type: 'number-computed'}, 'competences.esquive'),
      cinquieme({ key: 'combat.esquive_5', x: 92.2, y: 92.35, width: 1.5, fontSize: 0.5, type: 'number-computed'}, 'competences.esquive')
    ],
    page2: [
      { key: 'profil.description_1', x: 14, y: 6.5, width: 35.5, type: 'text-input'},
      { key: 'profil.description_2', x: 4.5, y: 8.8, width: 45, type: 'text-input'},
      { key: 'profil.ideologieEtCroyances_1', x: 20.5, y: 11.5, width: 29, type: 'text-input'},
      { key: 'profil.ideologieEtCroyances_2', x: 4.5, y: 14, width: 45, type: 'text-input'},
      { key: 'profil.personnesImportantes_1', x: 21, y: 16.5, width: 28.5, type: 'text-input'},
      { key: 'profil.personnesImportantes_2', x: 4.5, y: 19, width: 45, type: 'text-input'},
      { key: 'profil.lieuxSignificatifs_1', x: 17, y: 21.5, width: 32.5, type: 'text-input'},
      { key: 'profil.lieuxSignificatifs_2', x: 4.5, y: 24, width: 45, type: 'text-input'},
      { key: 'profil.biensPrecieux_1', x: 15.5, y: 26.5, width: 34, type: 'text-input'},
      { key: 'profil.biensPrecieux_2', x: 4.5, y: 28.7, width: 45, type: 'text-input'},

      { key: 'profil.traits_1', x: 55.5, y: 6.5, width: 40, type: 'text-input'},
      { key: 'profil.traits_2', x: 50.5, y: 8.8, width: 45, type: 'text-input'},
      { key: 'profil.sequellesEtCicatrices_1', x: 65, y: 11.5, width: 30.5, type: 'text-input'},
      { key: 'profil.sequellesEtCicatrices_2', x: 50.5, y: 14, width: 45, type: 'text-input'},
      { key: 'profil.phobiesEtManies_1', x: 64, y: 16.5, width: 31.5, type: 'text-input'},
      { key: 'profil.phobiesEtManies_2', x: 50.5, y: 19, width: 45, type: 'text-input'},
      { key: 'profil.ouvragesOccultesSortsEtArtefacts_1', x: 74.5, y: 21.5, width: 21, type: 'text-input'},
      { key: 'profil.ouvragesOccultesSortsEtArtefacts_2', x: 50.5, y: 24, width: 45, type: 'text-input'},
      { key: 'profil.rencontresAvecDesEntitesEtranges_1', x: 74.5, y: 26.5, width: 21, type: 'text-input'},
      { key: 'profil.rencontresAvecDesEntitesEtranges_2', x: 50.5, y: 28.7, width: 45, type: 'text-input'},

      { key: 'equipements.ligne_1_1', x: 6, y: 35, width: 23.5, type: 'text-input'},
      { key: 'equipements.ligne_1_2', x: 6, y: 37.5, width: 23.5, type: 'text-input'},
      { key: 'equipements.ligne_1_3', x: 6, y: 40.5, width: 23.5, type: 'text-input'},
      { key: 'equipements.ligne_1_4', x: 6, y: 43, width: 23.5, type: 'text-input'},
      { key: 'equipements.ligne_1_5', x: 6, y: 46, width: 23.5, type: 'text-input'},
      { key: 'equipements.ligne_1_6', x: 6, y: 48.5, width: 23.5, type: 'text-input'},

      { key: 'equipements.ligne_2_1', x: 32, y: 35, width: 23.5, type: 'text-input'},
      { key: 'equipements.ligne_2_2', x: 32, y: 37.5, width: 23.5, type: 'text-input'},
      { key: 'equipements.ligne_2_3', x: 32, y: 40.5, width: 23.5, type: 'text-input'},
      { key: 'equipements.ligne_2_4', x: 32, y: 43, width: 23.5, type: 'text-input'},
      { key: 'equipements.ligne_2_5', x: 32, y: 46, width: 23.5, type: 'text-input'},
      { key: 'equipements.ligne_2_6', x: 32, y: 48.5, width: 23.5, type: 'text-input'},

      { key: 'richesse.depensesCourantes_1', x: 71, y: 35, width: 23, type: 'text-input'},
      { key: 'richesse.depensesCourantes_2', x: 58, y: 37.5, width: 36, type: 'text-input'},
      { key: 'richesse.especes', x: 64, y: 40.5, width: 30, type: 'text-input'},
      { key: 'richesse.capital_1', x: 63, y: 43, width: 31, type: 'text-input'},
      { key: 'richesse.capital_2', x: 58, y: 46, width: 36, type: 'text-input'},
      { key: 'richesse.capital_3', x: 58, y: 48.5, width: 36, type: 'text-input'},

      { key: 'amisInvestigateurs.ami1_nom', x: 10.5, y: 54.3, width: 31, type: 'text-input'},
      { key: 'amisInvestigateurs.ami1_joueur', x: 12, y: 57, width: 11, type: 'text-input'},
      { key: 'amisInvestigateurs.ami1_scenario', x: 30, y: 57, width: 11.5, type: 'text-input'},
      { key: 'amisInvestigateurs.ami2_nom', x: 10.5, y: 59.8, width: 31, type: 'text-input'},
      { key: 'amisInvestigateurs.ami2_joueur', x: 12, y: 62.2, width: 11, type: 'text-input'},
      { key: 'amisInvestigateurs.ami2_scenario', x: 30, y: 62.2, width: 11.5, type: 'text-input'},
      { key: 'amisInvestigateurs.ami3_nom', x: 10.5, y: 65, width: 31, type: 'text-input'},
      { key: 'amisInvestigateurs.ami3_joueur', x: 12, y: 67.6, width: 11, type: 'text-input'},
      { key: 'amisInvestigateurs.ami3_scenario', x: 30, y: 67.6, width: 11.5, type: 'text-input'},
      { key: 'amisInvestigateurs.ami4_nom', x: 10.5, y: 70.7, width: 31, type: 'text-input'},
      { key: 'amisInvestigateurs.ami4_joueur', x: 12, y: 73.3, width: 11, type: 'text-input'},
      { key: 'amisInvestigateurs.ami4_scenario', x: 30, y: 73.3, width: 11.5, type: 'text-input'},

      { key: 'notes', x: 43.5, y: 53, width: 50.5, 'height': 23.2, fontSize: 0.8, type: 'text-zone'}
    ]
  }
}