import { OnePageSheetConfig } from 'src/app/model/sheet-config.model';

export const config: OnePageSheetConfig = {
    gameId: 'nains-et-jardins',
    sheetId: 'fr',
    pageConfig: {
      pages: [ 'page-1.png'],
      pageFormat: 'A4',
      pageOrientation: 'landscape',
      pageWidth: 100
    },
    content: {
      pageCount: 1,
      page1: [
        { key: 'identite.joueur', x: 10.5, y: 13.5, width: 13.8, rotate: -3.5, type: 'text-input'},
        { key: 'characterName', x: 10.5, y: 17.4, width: 13.3, rotate: -3.5, type: 'text-input'},
        { key: 'identite.ville', x: 10.5, y: 21.2, width: 13.6, rotate: -3.5, type: 'text-input'},
        { key: 'identite.jardinet', x: 11.0, y: 25.0, width: 12.5, rotate: -3.5, type: 'text-input'},
        { key: 'identite.clan', x: 11.0, y: 28.7, width: 11.8, rotate: -3.5, type: 'text-input'},

        { key: 'caracteristiques.force-densite', x: 24.2, y: 40.5, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques.solidite-elasticite', x: 24.2, y: 43.5, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques.agilite-grain', x: 24.2, y: 46.5, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques.dexterite-ciboulot', x: 24.2, y: 49.5, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques.intelligence-glamour', x: 24.2, y: 52.5, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques.raison-harmonie', x: 24.2, y: 55.5, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques.presence-foi', x: 24.2, y: 58.5, width: 2.2, type: 'number-input'},

        { key: 'caracteristiques-secondaires.points-de-platre', x: 24.2, y: 68.5, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques-secondaires.points-de-souillure', x: 24.2, y: 71.5, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques-secondaires.mofif-aux-dommages', x: 24.2, y: 74.5, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques-secondaires.points-de-jardins-totaux', x: 24.2, y: 77.0, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques-secondaires.points-de-nains-totaux', x: 24.2, y: 79.0, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques-secondaires.points-de-jardins-restants', x: 24.2, y: 81.5, width: 2.2, type: 'number-input'},
        { key: 'caracteristiques-secondaires.points-de-nains-restants', x: 24.2, y: 83.5, width: 2.2, type: 'number-input'},

        { key: 'apparence', x: 32.3, y: 15.0, width: 18.3, height: 29.5, type: 'text-zone'},
        { key: 'caractere', x: 52.5, y: 15.0, width: 18.5, height: 29.5, type: 'text-zone'},
        { key: 'gouts', x: 72.5, y: 15.0, width: 18.5, height: 11.5, type: 'text-zone'},
        { key: 'motivations', x: 72.5, y: 30.0, width: 18.5, height: 14.5, type: 'text-zone'},

        { key: 'aptitudes-naintuitives.01.label', x: 32.5, y: 52.0, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.01.value', x: 47.5, y: 52.0, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.02.label', x: 32.5, y: 54.5, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.02.value', x: 47.5, y: 54.5, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.03.label', x: 32.5, y: 57.0, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.03.value', x: 47.5, y: 57.0, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.04.label', x: 32.5, y: 59.5, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.04.value', x: 47.5, y: 59.5, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.05.label', x: 32.5, y: 62.0, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.05.value', x: 47.5, y: 62.0, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.06.label', x: 32.5, y: 64.5, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.06.value', x: 47.5, y: 64.5, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.07.label', x: 32.5, y: 67.0, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.07.value', x: 47.5, y: 67.0, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.08.label', x: 32.5, y: 69.5, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.08.value', x: 47.5, y: 69.5, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.09.label', x: 32.5, y: 72.0, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.09.value', x: 47.5, y: 72.0, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.10.label', x: 32.5, y: 74.5, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.10.value', x: 47.5, y: 74.5, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.11.label', x: 32.5, y: 77.0, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.11.value', x: 47.5, y: 77.0, width: 3.5, type: 'number-input'},
        { key: 'aptitudes-naintuitives.12.label', x: 32.5, y: 79.5, width: 15.0, type: 'text-input'},
        { key: 'aptitudes-naintuitives.12.value', x: 47.5, y: 79.5, width: 3.5, type: 'number-input'},

        { key: 'aptitudes-nainpromptues.01.label', x: 52.5, y: 52.0, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.01.value', x: 70.3, y: 52.0, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.02.label', x: 52.5, y: 54.5, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.02.value', x: 70.3, y: 54.5, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.03.label', x: 52.5, y: 57.0, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.03.value', x: 70.3, y: 57.0, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.04.label', x: 52.5, y: 59.5, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.04.value', x: 70.3, y: 59.5, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.05.label', x: 52.5, y: 62.0, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.05.value', x: 70.3, y: 62.0, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.06.label', x: 52.5, y: 64.5, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.06.value', x: 70.3, y: 64.5, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.07.label', x: 52.5, y: 67.0, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.07.value', x: 70.3, y: 67.0, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.08.label', x: 52.5, y: 69.5, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.08.value', x: 70.3, y: 69.5, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.09.label', x: 52.5, y: 72.0, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.09.value', x: 70.3, y: 72.0, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.10.label', x: 52.5, y: 74.5, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.10.value', x: 70.3, y: 74.5, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.11.label', x: 52.5, y: 77.0, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.11.value', x: 70.3, y: 77.0, width: 3.5, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.12.label', x: 52.5, y: 79.5, width: 17.8, type: 'text-input'},
        { key: 'aptitudes-nainpromptues.12.value', x: 70.3, y: 79.5, width: 3.5, type: 'text-input'},

        { key: 'notes', x: 76.0, y: 52.0, width: 21.0, height: 29.5, type: 'text-zone'},

        { key: 'possessions.01', x: 32.5, y: 86.9, width: 18.5, type: 'text-input'},
        { key: 'possessions.02', x: 32.5, y: 89.5, width: 18.5, type: 'text-input'},
        { key: 'possessions.03', x: 52.5, y: 86.9, width: 18.5, type: 'text-input'},
        { key: 'possessions.04', x: 52.5, y: 89.5, width: 18.5, type: 'text-input'},
        { key: 'possessions.05', x: 72.5, y: 86.9, width: 18.5, type: 'text-input'},
        { key: 'possessions.06', x: 72.5, y: 89.5, width: 18.5, type: 'text-input'},
      ],
    },
}